#!/usr/bin/env ruby

#
#  test_attach  --  Start a Neovim session and attach to it
#

require "neovim/remote"


module Neovim

  SOCKET = "/tmp/nvim-#$$.sock"

  system *%W(tmux split-window -dv nvim --listen #{SOCKET})
  sleep 1

  Remote.start_client ConnectionUnix, SOCKET do |c|
    c.command "e /etc/passwd"
    c.command "/home"
    b = c.get_current_buf
    puts b.inspect
    puts
    sleep 1
    puts b[1]
    w = c.get_current_win
    puts w.index
    puts b[w.line]
    c.command "bw"
    sleep 1
    e = c.evaluate "3*9"
    puts e.inspect
    sleep 1
    c.command "q"
  rescue Messager::Disconnected
    puts "done."
  end

end

