#!/usr/bin/env ruby

#
#  examples/passwords  --  Manage a file containing your passwords
#

# (C) 2025 Bertram Scharpf <software@bertram-scharpf.de>

require "neovim/host"


class Passwords

  PW_FILE = File.expand_path "~/.config/mypasswords.asc"
  RECIPIENT = "jdoe@example.com"

  def initialize debug: false
    @debug = debug
  end

  def run
    contents = get_contents.split $/
    Neovim::Remote.run_sub do |pw_dsl|
      pw_dsl.setup do |client|
        client.set_option shadafile: "NONE"
        client.set_option filetype: "dosini"
        client.put contents, "l", true, false
        client.command "1"
        client.get_current_line.empty? and client.del_current_line
        {
          "Save" => "rb_save",
          "Totp" => "rb_totp",
        }.each { |cmd,fn|
          client.command "command -buffer -nargs=0 %s call rpcrequest(%d,'%s')" % [ cmd, client.channel_id, fn]
        }
      end
      pw_dsl.register_handler "rb_save" do |client|
        File.rename PW_FILE, "#{PW_FILE}.bak" rescue nil
        IO.popen %W(gpg -a -r #{RECIPIENT} --encrypt -o #{PW_FILE}), "w" do |gpg|
          gpg.puts client.get_current_buf[1..]
        end
        File.chmod 0600, PW_FILE
      end
      pw_dsl.register_handler "rb_totp" do |client|
        require "potp"
        require "neovim/tools/copy"
        p = client.call_function "expand", [ "<cword>"]
        key = (POTP::TOTP.new p).now if p.notempty? and p.length % 4 == 0
        client.echo [ [ key]], true, {}
        xsel key
      rescue
        client.err_writeln "No OTP under cursor?"
      rescue ScriptError
        client.err_writeln $!.message
      end
    end
  end

  def get_contents
    r = IO.popen %W(gpg -d #{PW_FILE}), "r" do |gpg| gpg.read end
    r.notempty? or <<~EOT
      # Move the cursor to the OTP keyword and give the command `:Totp`.
      # The TOTP key will be displayed and further copied to the clipboard.

      [account "dummy"]
      name     = John Doe
      password = very$ecret
      optauth  = GYS5L3N3E4AAYNMN562LW76TMWHQBJ4A

      # As soon as you have set the `RECIPIENT` constant in the executable,
      # you may save this file calling the command `:Save`.
    EOT
  end

  new.run

end

